server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:test
    properties:
      rewriteBatchedStatements: true